config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/privacy_policy'
  get 'static_pages/terms_of_service'
  root 'calendars#new'

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }

  # Custom session routes
  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :new_line_user_session
    post '/login', to: 'users/sessions#create'
    get '/logout', to: 'users/sessions#destroy', as: :destroy_line_user_session
    get '/line_login', to: 'sessions#line_login', as: :login_with_line
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  # User profile route
  authenticated :user do
    get '/choose_registration', to: 'users/registrations#choose', as: :choose_registration
    get '/profile', to: 'users#profile', as: :user_profile
  end
  
  # Calendar routes
  resources :calendars, except: [:destroy, :update] do
    resources :schedules, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :bookmarks, only: [:index, :create, :destroy]
  end

  # Exercise routes
  resources :exercises, only: [:index, :show] do
    collection do
      get :autocomplete
    end
    resources :bookmarks, only: [:create, :destroy], shallow: false
  end
  
  # Registration routes
  resources :registrations, only: [:new]
  get '/line_registration', to: 'line_users#line_registration', as: :line_registration
  get '/email_registration', to: 'registrations#email_registration', as: :email_registration

  # LineUsers routes
  resources :line_users, only: [:show, :new, :create]

  # Customize routes
  resources :customizes, only: [:new, :edit, :create, :update]

  # Static pages routes
  scope controller: :static_pages do
    get :privacy_policy
    get :terms_of_service
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user, polymorphic: true

  has_many :calendar_users, dependent: :destroy
  has_many :users, through: :calendar_users, source: :user, source_type: 'User'
  has_many :line_users, through: :calendar_users, source: :user, source_type: 'LineUser'
  has_many :guest_users, through: :calendar_users, source: :user, source_type: 'GuestUser'
  has_many :schedules, dependent: :destroy

  validates :title, presence: true
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_or_line_user!, except: [:index, :show, :new, :create, :edit, :update, :destroy] 

  def index
    @calendars = Calendar.all
  end

  def new
    @calendar = Calendar.new
  end

  def create
    Rails.logger.debug "Create action called"
    @calendar = Calendar.new(calendar_params)
    @calendar.user ||= [current_user, current_guest, current_line_user].find(&:itself)

    if @calendar.user.nil?
      flash[:alert] = 'User must exist'
      render :new
      return
    end

    if @calendar.save
      Rails.logger.debug "Calendar saved successfully"
      if current_user
        @calendar.calendar_users.create(user: current_user)
      elsif current_guest
        @calendar.calendar_users.create(user: current_guest)
      elsif current_line_user
        @calendar.calendar_users.create(user: current_line_user)
      end

      if params[:schedule].present?
        Rails.logger.debug "Schedule params present, calling handle_successful_save"
        handle_successful_save
      else
        Rails.logger.debug "Redirecting to calendar path"
        redirect_to calendar_path(@calendar), notice: 'Calendar was successfully created.'
      end
    else
      error_messages = @calendar.errors.full_messages.join(', ')
      Rails.logger.error error_messages
      flash[:alert] = error_messages
      render :new
    end
  end

  def show
    @calendar = Calendar.find_by(id: params[:id])
    Rails.logger.debug "Debug - Calendar Found: #{@calendar.inspect}"

    if @calendar
      # カレンダーの表示権限を確認
      if authorized_to_view?(@calendar)
        session[:current_calendar_id] = @calendar.id
        @customize = Customize.find_by(calendar_id: @calendar.id)
        @events = @calendar.schedules.includes(:exercise)
  
        # @selected_dateを設定
        @selected_date = params[:date] ? Date.parse(params[:date]) : Date.today
        @schedules = @calendar.schedules.where(date: @selected_date) # 日付に基づくスケジュール表示
        @schedule = @calendar.schedules.new
        
      else
        Rails.logger.debug "Debug - Unauthorized to View Calendar"
        flash[:alert] = 'You are not authorized to view this calendar.'
        redirect_to calendars_path
      end
    else
      Rails.logger.debug "Debug - Calendar Not Found"
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
    expires_now
  end
  

  def edit
  end

  def update
    if @calendar.update(calendar_params)
      redirect_to calendars_path, notice: 'Calendar was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @calendar.destroy
    redirect_to calendars_path, notice: 'Calendar was successfully deleted.'
  end

  private

  def set_calendar
    @calendar = Calendar.find_by(id: params[:id])
    unless @calendar
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
  end

  def calendar_params
    params.require(:calendar).permit(:title, :image, :color, :image_url)
  end

  def schedule_params
    params.require(:schedule).permit(:start_time, :end_time, :exercise_id, :date, :repetitions, :duration)
  end

  def handle_successful_save
    @schedule = @calendar.schedules.build(schedule_params)
    if @schedule.save
      session[:current_calendar_id] = @calendar.id
      add_current_user_to_calendar if user_signed_in?
      redirect_to calendar_path(@calendar), notice: 'Calendar was successfully created.'
    else
      render :new
    end
  end

  def add_current_user_to_calendar
    @calendar.users << current_user unless @calendar.users.include?(current_user)
  end

  def add_current_line_user_to_calendar
    @calendar.line_users << current_line_user unless @calendar.line_users.include?(current_line_user)
  end

  def authorized_to_view?(calendar)
    Rails.logger.debug "Debug - Current User: #{current_user.inspect}"
    Rails.logger.debug "Debug - Current Line User: #{current_line_user.inspect}"
    Rails.logger.debug "Debug - Current Guest: #{current_guest.inspect}"
    Rails.logger.debug "Debug - Calendar User: #{calendar.user.inspect}"

    if current_user && calendar.users.exists?(id: current_user.id)
      Rails.logger.debug "Debug - Authorized as Current User"
      true
    elsif current_line_user && calendar.line_users.exists?(id: current_line_user.id)
      Rails.logger.debug "Debug - Authorized as Line User"
      true
    elsif current_guest && calendar.user == current_guest
      Rails.logger.debug "Debug - Authorized as Guest User"
      true  # GuestUserの場合はhas_oneのため単一カレンダーをチェック
    else
      Rails.logger.debug "Debug - Not Authorized"
      false
    end
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_with(model: @calendar, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :color %>
    <%= form.text_field :color, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/calendars/index.html.erb
  <h1 class="calendar-header">Calendars#index</h1>

<%= content_tag :div, class: "simple-calendar #{session[:calendar_color]}" do %>
  <%= month_calendar events: @events do |date, events| %>
    <div class="calendar-date"><%= date.day %></div>
    <div class="event-list">
      <% events.each do |event| %>
        <div class="event-item"><%= event.title %></div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/calendars/new.html.erb
<%= form_with(model: @calendar, url: calendars_path, method: :post, local: true) do |form| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>
      <ul>
        <% @calendar.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Calendar' %>
  </div>
<% end %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<%= content_tag :div, class: "simple-calendar #{session[:calendar_color]}" do %>
  <%= month_calendar events: @events do |date, events| %>
    <div class="calendar-date" data-date="<%= date %>" data-calendar-id="<%= @calendar.id %>">
      <%= link_to date.day, "#", class: 'date-link', data: { bs_toggle: 'modal', bs_target: '#scheduleModal' } %>
    </div>
    <div class="event-list">
      <% events.each do |event| %>
        <div class="event-item">
          <%= link_to event.exercise.name, calendar_schedule_path(@calendar, event), class: 'exercise-link' %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<!-- スケジュールモーダル -->
<%= render 'schedules/schedule_modal' %>

<!-- 編集モーダル -->
<%= render 'schedules/edit_modal' %>